name: Pull Request Check

on: [ pull_request ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Apt Install ...
        run: sudo apt-get update; sudo apt-get install libpcap-dev # install libpcap for gopcap-sdk
      - name: Show Project ...
        run: ls -al
      - name: Compile
        run: make build
      - name: Test
        run: make test